---

# current -> /appli/releases/2.1.0/
# ├── releases
# │   ├── 1.0.0
# │   ├── 1.0.1
# │   ├── 1.0.2
# │   ├── 1.2.0
# │   └── 2.1.0
# ├── revisions.log
# └── shared
#     └── <linked_files and linked_dirs>
#
# project root : /appli
# apache doc root : /appli/current/web

- name: Create worksapce
  file:
    path: "{{ temp_workspace }}"
    state: directory
    mode: 0750
  when: not dev_env

- name: Download sources code archive
  get_url:
    url: "{{ github_sources_url }}/archive/{{ application_branch }}.zip"
    dest: "{{ temp_workspace }}/livlyonSources-{{ application_branch | regex_replace('/','-') }}.zip"
  when: not dev_env

- name: Unzip {{ application_branch }} archive
  become: yes
  unarchive:
    src: "{{ temp_workspace }}/livlyonSources-{{ application_branch | regex_replace('/','-') }}.zip"
    dest: "{{ temp_workspace }}/"
    force: yes
    remote_src: yes
    owner: "{{ apache_user }}"
    group: "{{ apache_group }}"
  when: not dev_env

- name: Read composer.json file.
  shell: "cat {{ temp_workspace }}/liv_lyon_sources-{{ application_branch | regex_replace('/','-') }}/composer.json"
  register: json
  when: not dev_env

- name: get version number
  set_fact:
    app_version: "{{ (json.stdout | from_json).version }}"
  when: not dev_env

- name: Ansible check file exists example.
  stat:
    path: "{{ application_path }}/releases/{{ app_version }}/"
  register: app_version_exist
  when: not dev_env

- name: Create Capistrano Directory structure
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ apache_user }}"
    group: "{{ apache_group }}"
    mode: 0755
  with_items:
    - "{{ application_path }}"
    - "{{ application_path }}/logs"
    - "{{ application_path }}/current"
    - "{{ application_path }}/shared"
    - "{{ application_path }}/shared/places-img"
    - "{{ application_path }}/shared/events-img"
    - "{{ application_path }}/releases"
    - "{{ application_path }}/releases/{{ app_version }}"
  become: yes
  when: not dev_env

- name: Copy {{ application_branch }} archive content in releases path
  shell: "mv -f -u {{ temp_workspace }}/liv_lyon_sources-{{ application_branch | regex_replace('/','-') }}/* {{ application_path }}/releases/{{ app_version }}/"
  when:
    - 'not dev_env'
    - 'not app_version_exist.stat.exists'

- name: Create parameters.yml
  template:
    src: parameters.yml.j2
    dest: "{{ application_path }}/releases/{{ app_version }}/app/config/parameters.yml"
  when: not dev_env

- name: Ensure Apache is sessions directory owner
  become: yes
  shell: "chmod 777 -R {{ application_path }}/releases/{{ app_version }}/web/"
  when: not dev_env

- name: Composer install
  shell: 'composer install --no-scripts'
  args:
    chdir: "{{ application_path }}/releases/{{ app_version }}"
  when: not dev_env

- name: Install assets
  shell: "php bin/console assets:install"
  args:
    chdir: "{{ application_path }}/releases/{{ app_version }}"

- name: Cache clear Prod
  become: yes
  shell: rm -rf {{ application_path }}/releases/{{ app_version }}/var/cache/prod
  when: not dev_env
  args:
    chdir: "{{ application_path }}/releases/{{ app_version }}"
  when: not dev_env

- name: delete logs path
  shell: "rm -rf var/logs"
  args:
    chdir: "{{ application_path }}/releases/{{ app_version }}"
  when: not dev_env

- name: Create symlink
  become: yes
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ apache_user }}"
    group: "{{ apache_group }}"
    mode: 0755
    state: link
    force: yes
  with_items:
    - { dest: '{{ application_path }}/releases/{{ app_version }}/var/logs', src: '{{ application_path }}/logs/' }
    - { dest: '{{ application_path }}/releases/{{ app_version }}/web/img/event' , src: '{{ application_path }}/shared/events-img/' }
    - { dest: '{{ application_path }}/releases/{{ app_version }}/web/img/place' , src: '{{ application_path }}/shared/places-img/' }
    - { dest: '{{ application_path }}/current', src: '{{ application_path }}/releases/{{ app_version }}/' }
    - { dest: '/var/www/html/web', src: '{{ application_path }}/current/web/' }
  when: not dev_env

- name: Ensure Apache is sessions directory owner
  become: yes
  file:
    path: '/var/lib/php/sessions'
    state: directory
    owner: '{{ apache_user }}'
    group: '{{ apache_group }}'
    recurse: yes
    mode: 775
  when: not dev_env

- name: Ensure Apache is cache directory owner
  become: yes
  file:
    path: '{{ application_path }}/releases/{{ app_version }}/var/cache/'
    state: directory
    recurse: yes
    owner: '{{ apache_user }}'
    group: '{{ apache_group }}'
    mode: 775
  when: not dev_env

- name: Ensure Apache is cache directory owner
  become: yes
  file:
    path: '{{ application_path }}/releases/{{ app_version }}/var/logs'
    state: directory
    recurse: yes
    owner: '{{ apache_user }}'
    group: '{{ apache_group }}'
    mode: 775
  when: not dev_env

- name: Update database schema for prod
  shell: php bin/console doctrine:schema:update -f
  args:
    chdir: "{{ application_path }}/releases/{{ app_version }}"
  when:
    - not dev_env
    - update_db_schem == "yes"

- name: Update database schema for dev
  shell: php bin/console doctrine:schem:update -f
  when: dev_env
  args:
    chdir: "{{ application_path }}"

- name: Ensure app_dev.php access from host
  become: yes
  template:
      src: app_dev.php.j2
      dest: "{{ application_path }}/web/app_dev.php"
  when: dev_env

- name: Load Fixtures
  shell: php bin/console doctrine:fixtures:load -n
  when: dev_env
  args:
    chdir: "{{ application_path }}"

- name: Delete worksapce
  file:
    path: "{{ temp_workspace }}"
    state: absent
  when: not dev_env
