---
- name: Clone sources code
  git:
    repo: '{{ github_repo_sources }}'
    dest: '{{ application_path }}'
    version: '{{ application_version }}'
  when: not dev_env

- name: Create app/config/parameters.yml
  become: yes
  template:
      src: parameters.yml.j2
      dest: "{{ application_path }}/app/config/parameters.yml"

- name: Composer Install
  shell: cd {{ application_path }} && composer install --no-scripts --optimize-autoloader

- name: Cache clear Prod && Dev
  shell: cd {{ application_path }} && php bin/console c:c --env={{ item }}
  with_items:
    - "dev"
    - "prod"

- name: Update database schema
  shell: cd {{ application_path }} && php bin/console doctrine:schem:update -f

- name: Ensure app_dev.php access from host
  become: yes
  template:
      src: app_dev.php.j2
      dest: "{{ application_path }}/web/app_dev.php"
  when: dev_env

- name: Ensure Apache is cache directory owner
  become: yes
  file:
    path: "{{ application_path }}/var/cache/"
    state: directory
    owner: '{{ apache_user }}'
    group: '{{ apache_group }}'
    mode: 775

- name: Ensure Apache is sessions directory owner
  become: yes
  file:
    path: '{{ application_path }}/var/sessions'
    state: directory
    owner: '{{ apache_user }}'
    group: '{{ apache_group }}'
    mode: 775

- name: Ensure Apache is logs directory owner
  become: yes
  file:
    path: '{{ apache_user }}/var/logs'
    state: directory
    owner: '{{ apache_user }}'
    group: '{{ apache_group }}'
    mode: 775

- name: Load Fixtures
  shell: cd {{ application_path }} && php bin/console doctrine:fixtures:load -n
  when: dev_env
