############################################
##                                        ##
##     DEVELOPEMENT ENV PARAMETERS        ##
##                                        ##
############################################

###########################
##   SYSTEM PARAMETERS   ##
###########################
use_calife: false
use_epel: true
use_scl: true
use_softwarecollections: true
use_repo_doit: false
remount_filesystems: false

hebergement:          "local"
vagrant:              true
proxy_on:             false

server:
    download_path: /tmp

system_timezone: "Europe/Paris"
dev_env: true

#############################
##    App Configuration    ##
#############################
application_version: develop
application_path: /vagrant/sources

cache_path: '{{ application_path }}/var/cache'
sessions_path: '{{ application_path }}/var/sessions'
logs_path: '{{ application_path }}/var/logs'


parameters:
    database_host: 127.0.0.1
    database_port: null
    database_name: liv_lyon_data
    database_user: liv_lyon_app
    database_password: notsecurepasswordchangeitforprod
    mailer_transport: gmail
    mailer_host: 127.0.0.1
    mailer_user: mailer.dev.brice@gmail.com
    mailer_password: bar
    secret: MySecretVerySecret
    paypal_env: sandbox #or production

#############################
##   Apache Configuration  ##
#############################
apache_listen_ip: "*"
apache_listen_port: 80
apache_listen_port_ssl: 443
apache_user: vagrant
apache_group: vagrant
php_fpm_pool_user: {{ apache_user }}
php_fpm_pool_group: {{ apache_group }}

apache_vhosts:
  # Additional properties:
  # 'serveradmin, serveralias, allow_override, options, extra_parameters'.
  - servername: "local.dev"
    documentroot: "{{ application_path }}/web"
    extra_parameters: |
      ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000{{ application_path }}/web"

apache_user_and_group:
  - {
    regexp: "^User ",
    line: "User {{ apache_user }}"
  }
  - {
    regexp: "^Group ",
    line: "Group {{ apache_group }}"
  }
#############################
##    MYSLQ Configuration  ##
#############################
mysql_databases:
   - name: "{{ parameters.database_name }}"
     collation: utf8_general_ci
     encoding: utf8
     replicate: 1

# Users.
mysql_users:
  # Removes all anonymous user accounts
  - name: ''
    host_all: yes
    password: ''
    state: absent

  - name: '{{ parameters.database_user }}'
    host: '127.0.0.1'
    all_host: 'yes'
    password: '{{ parameters.database_password }}'
    priv: '{{ parameters.database_name }}.*:ALL'
    update_password: always
