############################################
##                                        ##
##     DEVELOPEMENT ENV PARAMETERS        ##
##                                        ##
############################################
#############################
##Deployment Configuration ##
#############################
github_sources_url: "https://github.com/BriceMichalski/liv_lyon_sources"
temp_workspace: /tmp/deployment-workspace
application_branch: feature/map
application_path: /appli
dev_env: false

#############################
##    App Configuration    ##
#############################
parameters:
    database_host: 127.0.0.1
    database_port: null
    database_name: MAIN
    database_user: liv_app
    database_password: livapppass2019
    mailer_transport: gmail
    mailer_host: null
    mailer_user: mailer.dev.brice@gmail.com
    mailer_password: bar
    secret: livlyon2019
    paypal_env: sandbox #or production

###########################
##   SYSTEM PARAMETERS   ##
###########################
use_calife: false
use_epel: true
use_scl: true
use_softwarecollections: true
use_repo_doit: false
remount_filesystems: false
hebergement:          "local"
system_timezone: "Europe/Paris"

###########################
##   MYSQL PARAMETERS    ##
###########################
mysql_root_password: root
mysql_databases:
  - name: MAIN
    encoding: utf8
    collation: utf8_general_ci
mysql_users:
  - name: liv_app
    host: "%"
    password: livapppass2019
    priv: "MAIN.*:ALL"

#############################
##   Apache Configuration  ##
#############################
apache_listen_port: 80
apache_vhosts_version: "2.4"
apache_user: vagrant
apache_group: vagrant
apache_vhosts:
  - servername: "local.dev"
    documentroot: "{{ application_path}}/current/web"
    extra_parameters: |
          ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000{{ application_path}}/current/web"

#############################
##   PHP Configuration     ##
#############################
php_version: '7.2'
php_memory_limit: "128M"
php_max_execution_time: "90"
php_upload_max_filesize: "256M"
php_packages:
  - php
  - php-cli
  - php-common
  - php-devel
  - php-gd
  - php-mbstring
  - php-pdo
  - php-pecl-apcu
  - php-xml
  - php-intl
php_enable_php_fpm: true
php_fpm_pool_user: '{{ apache_user }}'
php_fpm_pool_group: '{{ apache_group }}'
